spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

order-service:
  url: http://localhost:8002/order

product-service:
  url: http://localhost:8001/product